apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-spinnaker-deployment
  labels:
    app: cicd-test-spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test-spinnaker
  template:
    metadata:
      labels:
        app: cicd-test-spinnaker
    spec:
      containers:
        - name: cicd-test-spinnaker
          image: eu.gcr.io/docker-registry/cicd-test-spin
          ports:
            - containerPort: 8080
