apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-test-spinnaker
  name: cicd-test-spinnaker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test-spinnaker
  template:
    metadata:
      labels:
        app: cicd-test-spinnaker
    spec:
      containers:
        - image: eu.gcr.io/duedil-registry/cicd-test-spin
          name: cicd-test-spinnaker
          env:
            - name: STAGE
              value:
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
