steps:
  - name: 'openjdk:10-jre-slim'
    entrypoint: 'bash'
    args: ['-c', './gradlew clean test']
    id: 'cicd-test-test'
  - name: 'openjdk:10-jre-slim'
    entrypoint: 'bash'
    args: ['-c', './gradlew clean build']
    id: 'cicd-test-build'
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', "if[$BRANCH_NAME = 'master'] \
      docker build . -f src/buildscripts/Dockerfile -t gcr.io/sandpit-environment/github.com/duedil-ltd/cicd-test:$SHORT_SHA && docker push \
    else \
      echo 'Not on master, skiping Docker step' \
    fi"
    ]
    id: 'cicd-test-docker'

